int bochs_keys[] = {
    BX_KEY_UNHANDLED, // KBD_NONE = 0x00,
    BX_KEY_UNHANDLED, // KBD_ERR_OVF = 0x01,
	BX_KEY_UNHANDLED, // 0x2
	BX_KEY_UNHANDLED, // 0x3
    BX_KEY_A, // KBD_A = 0x04,
    BX_KEY_B, // KBD_B = 0x05,
    BX_KEY_C, // KBD_C = 0x06,
    BX_KEY_D, // KBD_D = 0x07,
    BX_KEY_E, // KBD_E = 0x08,
    BX_KEY_F, // KBD_F = 0x09,
    BX_KEY_G, // KBD_G = 0x0a,
    BX_KEY_H, // KBD_H = 0x0b,
    BX_KEY_I, // KBD_I = 0x0c,
    BX_KEY_J, // KBD_J = 0x0d,
    BX_KEY_K, // KBD_K = 0x0e,
    BX_KEY_L, // KBD_L = 0x0f,
    BX_KEY_M, // KBD_M = 0x10,
    BX_KEY_N, // KBD_N = 0x11,
    BX_KEY_O, // KBD_O = 0x12,
    BX_KEY_P, // KBD_P = 0x13,
    BX_KEY_Q, // KBD_Q = 0x14,
    BX_KEY_R, // KBD_R = 0x15,
    BX_KEY_S, // KBD_S = 0x16,
    BX_KEY_T, // KBD_T = 0x17,
    BX_KEY_U, // KBD_U = 0x18,
    BX_KEY_V, // KBD_V = 0x19,
    BX_KEY_W, // KBD_W = 0x1a,
    BX_KEY_X, // KBD_X = 0x1b,
    BX_KEY_Y, // KBD_Y = 0x1c,
    BX_KEY_Z, // KBD_Z = 0x1d,

    BX_KEY_1, // KBD_1 = 0x1e,
    BX_KEY_2, // KBD_2 = 0x1f,
    BX_KEY_3, // KBD_3 = 0x20,
    BX_KEY_4, // KBD_4 = 0x21,
    BX_KEY_5, // KBD_5 = 0x22,
    BX_KEY_6, // KBD_6 = 0x23,
    BX_KEY_7, // KBD_7 = 0x24,
    BX_KEY_8, // KBD_8 = 0x25,
    BX_KEY_9, // KBD_9 = 0x26,
    BX_KEY_0, // KBD_0 = 0x27,

    BX_KEY_ENTER, // KBD_ENTER = 0x28,
    BX_KEY_ESC, // KBD_ESC = 0x29,
    BX_KEY_BACKSPACE, // KBD_BACKSPACE = 0x2a,
    BX_KEY_TAB, // KBD_TAB = 0x2b,
    BX_KEY_SPACE, // KBD_SPACE = 0x2c,
    BX_KEY_MINUS, // KBD_MINUS = 0x2d,
    BX_KEY_EQUALS, // KBD_EQUAL = 0x2e,
    BX_KEY_LEFT_BRACKET, // KBD_LEFTBRACE = 0x2f,
    BX_KEY_RIGHT_BRACKET, // KBD_RIGHTBRACE = 0x30,
    BX_KEY_LEFT_BACKSLASH, // KBD_BACKSLASH = 0x31,
    BX_KEY_UNHANDLED, // KBD_HASHTILDE = 0x32,                                      // what
    BX_KEY_SEMICOLON, // KBD_SEMICOLON = 0x33,
    BX_KEY_SINGLE_QUOTE, // KBD_APOSTROPHE = 0x34,
    BX_KEY_GRAVE, // KBD_GRAVE = 0x35,
    BX_KEY_COMMA, // KBD_COMMA = 0x36,
    BX_KEY_PERIOD, // KBD_DOT = 0x37,
    BX_KEY_SLASH, // KBD_SLASH = 0x38,
    BX_KEY_CAPS_LOCK, // KBD_CAPSLOCK = 0x39,

    BX_KEY_F1, // KBD_F1 = 0x3a,
    BX_KEY_F2, // KBD_F2 = 0x3b,
    BX_KEY_F3, // KBD_F3 = 0x3c,
    BX_KEY_F4, // KBD_F4 = 0x3d,
    BX_KEY_F5, // KBD_F5 = 0x3e,
    BX_KEY_F6, // KBD_F6 = 0x3f,
    BX_KEY_F7, // KBD_F7 = 0x40,
    BX_KEY_F8, // KBD_F8 = 0x41,
    BX_KEY_F9, // KBD_F9 = 0x42,
    BX_KEY_F10, // KBD_F10 = 0x43,
    BX_KEY_F11, // KBD_F11 = 0x44,
    BX_KEY_F12, // KBD_F12 = 0x45,

    BX_KEY_PRINT, // KBD_SYSRQ = 0x46,
    BX_KEY_SCRL_LOCK, // KBD_SCROLLLOCK = 0x47,
    BX_KEY_PAUSE, // KBD_PAUSE = 0x48,
    BX_KEY_INSERT, // KBD_INSERT = 0x49,
    BX_KEY_HOME, // KBD_HOME = 0x4a,
    BX_KEY_PAGE_UP, // KBD_PAGEUP = 0x4b,
    BX_KEY_DELETE, // KBD_DELETE = 0x4c,
    BX_KEY_END, // KBD_END = 0x4d,
    BX_KEY_PAGE_DOWN, // KBD_PAGEDOWN = 0x4e,
    BX_KEY_RIGHT, // KBD_RIGHT = 0x4f,
    BX_KEY_LEFT, // KBD_LEFT = 0x50,
    BX_KEY_DOWN, // KBD_DOWN = 0x51,
    BX_KEY_UP, // KBD_UP = 0x52,

    BX_KEY_NUM_LOCK, // KBD_NUMLOCK = 0x53,
    BX_KEY_KP_DIVIDE, // KBD_KPSLASH = 0x54,
    BX_KEY_KP_MULTIPLY, // KBD_KPASTERISK = 0x55,
    BX_KEY_KP_SUBTRACT, // KBD_KPMINUS = 0x56,
    BX_KEY_KP_ADD,// KBD_KPPLUS = 0x57,
    BX_KEY_KP_ENTER, // KBD_KPENTER = 0x58,
    BX_KEY_KP_END, // KBD_KP1 = 0x59,
    BX_KEY_KP_DOWN, // KBD_KP2 = 0x5a,
    BX_KEY_KP_PAGE_DOWN, // KBD_KP3 = 0x5b,
    BX_KEY_KP_LEFT, // KBD_KP4 = 0x5c,
    BX_KEY_KP_5, // KBD_KP5 = 0x5d,
    BX_KEY_KP_RIGHT,// KBD_KP6 = 0x5e,
    BX_KEY_KP_HOME, // KBD_KP7 = 0x5f,
    BX_KEY_KP_UP, // KBD_KP8 = 0x60,
    BX_KEY_KP_PAGE_UP, // KBD_KP9 = 0x61,
    BX_KEY_KP_INSERT, // KBD_KP0 = 0x62,
    BX_KEY_KP_DELETE, // KBD_KPDOT = 0x63,

    BX_KEY_UNHANDLED, // KBD_102ND = 0x64,
    BX_KEY_UNHANDLED, // KBD_COMPOSE = 0x65,
    BX_KEY_POWER_POWER, // KBD_POWER = 0x66,
    BX_KEY_POWER_POWER, // KBD_KPEQUAL = 0x67,

    BX_KEY_UNHANDLED, // KBD_F13 = 0x68,
    BX_KEY_UNHANDLED, // KBD_F14 = 0x69,
    BX_KEY_UNHANDLED, // KBD_F15 = 0x6a,
    BX_KEY_UNHANDLED, // KBD_F16 = 0x6b,
    BX_KEY_UNHANDLED, // KBD_F17 = 0x6c,
    BX_KEY_UNHANDLED, // KBD_F18 = 0x6d,
    BX_KEY_UNHANDLED, // KBD_F19 = 0x6e,
    BX_KEY_UNHANDLED, // KBD_F20 = 0x6f,
    BX_KEY_UNHANDLED, // KBD_F21 = 0x70,
    BX_KEY_UNHANDLED, // KBD_F22 = 0x71,
    BX_KEY_UNHANDLED, // KBD_F23 = 0x72,
    BX_KEY_UNHANDLED, // KBD_F24 = 0x73,

    BX_KEY_UNHANDLED, // KBD_OPEN = 0x74,
    BX_KEY_UNHANDLED, // KBD_HELP = 0x75,
    BX_KEY_UNHANDLED, // KBD_PROPS = 0x76,
    BX_KEY_UNHANDLED, // KBD_FRONT = 0x77,
    BX_KEY_UNHANDLED, // KBD_STOP = 0x78,
    BX_KEY_UNHANDLED, // KBD_AGAIN = 0x79,
    BX_KEY_UNHANDLED, // KBD_UNDO = 0x7a,
    BX_KEY_UNHANDLED, // KBD_CUT = 0x7b,
    BX_KEY_UNHANDLED, // KBD_COPY = 0x7c,
    BX_KEY_UNHANDLED, // KBD_PASTE = 0x7d,
    BX_KEY_UNHANDLED, // KBD_FIND = 0x7e,
    BX_KEY_UNHANDLED, // KBD_MUTE = 0x7f,
    BX_KEY_UNHANDLED, // KBD_VOLUMEUP = 0x80,
    BX_KEY_UNHANDLED, // KBD_VOLUMEDOWN = 0x81,
    BX_KEY_UNHANDLED, // KBD_CAPSLOCK_ACTIVE = 0x82 ,
    BX_KEY_UNHANDLED, // KBD_NUMLOCK_ACTIVE = 0x83 ,
    BX_KEY_UNHANDLED, // KBD_SCROLLLOCK_ACTIVE = 0x84 ,
    BX_KEY_UNHANDLED, // KBD_KPCOMMA = 0x85,
    
    BX_KEY_UNHANDLED, // 0x86
	BX_KEY_UNHANDLED, // 0x87
	BX_KEY_UNHANDLED, // 0x88
	BX_KEY_UNHANDLED, // 0x89
	BX_KEY_UNHANDLED, // 0x8a
	BX_KEY_UNHANDLED, // 0x8b
	BX_KEY_UNHANDLED, // 0x8c
	BX_KEY_UNHANDLED, // 0x8d
	BX_KEY_UNHANDLED, // 0x8e
	BX_KEY_UNHANDLED, // 0x8f
	BX_KEY_UNHANDLED, // 0x90
	BX_KEY_UNHANDLED, // 0x91
	BX_KEY_UNHANDLED, // 0x92
	BX_KEY_UNHANDLED, // 0x93
	BX_KEY_UNHANDLED, // 0x94
	BX_KEY_UNHANDLED, // 0x95
	BX_KEY_UNHANDLED, // 0x96
	BX_KEY_UNHANDLED, // 0x97
	BX_KEY_UNHANDLED, // 0x98
	BX_KEY_UNHANDLED, // 0x99
	BX_KEY_UNHANDLED, // 0x9a
	BX_KEY_UNHANDLED, // 0x9b
	BX_KEY_UNHANDLED, // 0x9c
	BX_KEY_UNHANDLED, // 0x9d
	BX_KEY_UNHANDLED, // 0x9e
	BX_KEY_UNHANDLED, // 0x9f
	BX_KEY_UNHANDLED, // 0xa0
	BX_KEY_UNHANDLED, // 0xa1
	BX_KEY_UNHANDLED, // 0xa2
	BX_KEY_UNHANDLED, // 0xa3
	BX_KEY_UNHANDLED, // 0xa4
	BX_KEY_UNHANDLED, // 0xa5
	BX_KEY_UNHANDLED, // 0xa6
	BX_KEY_UNHANDLED, // 0xa7
	BX_KEY_UNHANDLED, // 0xa8
	BX_KEY_UNHANDLED, // 0xa9
	BX_KEY_UNHANDLED, // 0xaa
	BX_KEY_UNHANDLED, // 0xab
	BX_KEY_UNHANDLED, // 0xac
	BX_KEY_UNHANDLED, // 0xad
	BX_KEY_UNHANDLED, // 0xae
	BX_KEY_UNHANDLED, // 0xaf
	BX_KEY_UNHANDLED, // 0xb0
	BX_KEY_UNHANDLED, // 0xb1
	BX_KEY_UNHANDLED, // 0xb2
	BX_KEY_UNHANDLED, // 0xb3
	BX_KEY_UNHANDLED, // 0xb4
	BX_KEY_UNHANDLED, // 0xb5
    BX_KEY_UNHANDLED, // KBD_KPLEFTPAREN = 0xb6,
    BX_KEY_UNHANDLED, // KBD_KPRIGHTPAREN = 0xb7,
	BX_KEY_UNHANDLED, // 0xb8
	BX_KEY_UNHANDLED, // 0xb9
	BX_KEY_UNHANDLED, // 0xba
	BX_KEY_UNHANDLED, // 0xbb
	BX_KEY_UNHANDLED, // 0xbc
	BX_KEY_UNHANDLED, // 0xbd
	BX_KEY_UNHANDLED, // 0xbe
	BX_KEY_UNHANDLED, // 0xbf
	BX_KEY_UNHANDLED, // 0xc0
	BX_KEY_UNHANDLED, // 0xc1
	BX_KEY_UNHANDLED, // 0xc2
	BX_KEY_UNHANDLED, // 0xc3
	BX_KEY_UNHANDLED, // 0xc4
	BX_KEY_UNHANDLED, // 0xc5
	BX_KEY_UNHANDLED, // 0xc6
	BX_KEY_UNHANDLED, // 0xc7
	BX_KEY_UNHANDLED, // 0xc8
	BX_KEY_UNHANDLED, // 0xc9
	BX_KEY_UNHANDLED, // 0xca
	BX_KEY_UNHANDLED, // 0xcb
	BX_KEY_UNHANDLED, // 0xcc
	BX_KEY_UNHANDLED, // 0xcd
	BX_KEY_UNHANDLED, // 0xce
	BX_KEY_UNHANDLED, // 0xcf
	BX_KEY_UNHANDLED, // 0xd0
	BX_KEY_UNHANDLED, // 0xd1
	BX_KEY_UNHANDLED, // 0xd2
	BX_KEY_UNHANDLED, // 0xd3
	BX_KEY_UNHANDLED, // 0xd4
	BX_KEY_UNHANDLED, // 0xd5
	BX_KEY_UNHANDLED, // 0xd6
	BX_KEY_UNHANDLED, // 0xd7
	BX_KEY_UNHANDLED, // 0xd8
	BX_KEY_UNHANDLED, // 0xd9
	BX_KEY_UNHANDLED, // 0xda
	BX_KEY_UNHANDLED, // 0xdb
	BX_KEY_UNHANDLED, // 0xdc
	BX_KEY_UNHANDLED, // 0xdd
	BX_KEY_UNHANDLED, // 0xde
	BX_KEY_UNHANDLED, // 0xdf
    BX_KEY_CTRL_L, // KBD_LEFTCTRL = 0xe0,
    BX_KEY_SHIFT_L, // KBD_LEFTSHIFT = 0xe1,
    BX_KEY_ALT_L, // KBD_LEFTALT = 0xe2,
    BX_KEY_WIN_L, // KBD_LEFTMETA = 0xe3,
    BX_KEY_CTRL_R, // KBD_RIGHTCTRL = 0xe4,
    BX_KEY_SHIFT_R, // KBD_RIGHTSHIFT = 0xe5,
    BX_KEY_ALT_R, // KBD_RIGHTALT = 0xe6,
    BX_KEY_WIN_R, // KBD_RIGHTMETA = 0xe7,

    BX_KEY_UNHANDLED, // KBD_MEDIA_PLAYPAUSE = 0xe8,
    BX_KEY_UNHANDLED, // KBD_MEDIA_STOPCD = 0xe9,
    BX_KEY_UNHANDLED, // KBD_MEDIA_PREVIOUSSONG = 0xea,
    BX_KEY_UNHANDLED, // KBD_MEDIA_NEXTSONG = 0xeb,
    BX_KEY_UNHANDLED, // KBD_MEDIA_EJECTCD = 0xec,
    BX_KEY_UNHANDLED, // KBD_MEDIA_VOLUMEUP = 0xed,
    BX_KEY_UNHANDLED, // KBD_MEDIA_VOLUMEDOWN = 0xee,
    BX_KEY_UNHANDLED, // KBD_MEDIA_MUTE = 0xef,
    BX_KEY_UNHANDLED, // KBD_MEDIA_WWW = 0xf0,
    BX_KEY_UNHANDLED, // KBD_MEDIA_BACK = 0xf1,
    BX_KEY_UNHANDLED, // KBD_MEDIA_FORWARD = 0xf2,
    BX_KEY_UNHANDLED, // KBD_MEDIA_STOP = 0xf3,
    BX_KEY_UNHANDLED, // KBD_MEDIA_FIND = 0xf4,
    BX_KEY_UNHANDLED, // KBD_MEDIA_SCROLLUP = 0xf5,
    BX_KEY_UNHANDLED, // KBD_MEDIA_SCROLLDOWN = 0xf6,
    BX_KEY_UNHANDLED, // KBD_MEDIA_EDIT = 0xf7,
    BX_KEY_UNHANDLED, // KBD_MEDIA_SLEEP = 0xf8,
    BX_KEY_UNHANDLED, // KBD_MEDIA_COFFEE = 0xf9,
    BX_KEY_UNHANDLED, // KBD_MEDIA_REFRESH = 0xfa,
    BX_KEY_UNHANDLED, // KBD_MEDIA_CALC = 0xfb
};